# Generated by Django 3.2.11 on 2023-03-11 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_team_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.EmailField(default='rewasr@gera.pl', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='opis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nazwa',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
