# Generated by Django 3.2.11 on 2023-03-28 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_tournament_ilosc_druzyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='ilosc_druzyn',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('16', '16'), ('32', '32')], max_length=100),
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
