# Generated by Django 3.2.11 on 2023-03-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230328_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Powiadomienie',
            new_name='Powiadomienia',
        ),
    ]
