# Generated by Django 3.2.11 on 2023-03-12 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_team_punkty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='druzyny',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format_rozgrywek',
            field=models.CharField(blank=True, choices=[('5vs5', '5vs5'), ('2vs2', '2vs2'), ('1vs1', '1vs1')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ilosc_druzyn',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='nagroda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rodzaj_gry',
            field=models.CharField(blank=True, choices=[('League of Legends', 'League of Legends'), ('Valorant', 'Valorant'), ('Counter-Strike: Global Offensive', 'Counter-Strike: Global Offensive')], max_length=100, null=True),
        ),
    ]
