# Generated by Django 3.2.11 on 2023-03-12 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230312_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='opis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='creator',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format_rozgrywek',
            field=models.CharField(choices=[('5vs5', '5vs5'), ('2vs2', '2vs2'), ('1vs1', '1vs1')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ilosc_druzyn',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rodzaj_gry',
            field=models.CharField(choices=[('League of Legends', 'League of Legends'), ('Valorant', 'Valorant'), ('Counter-Strike: Global Offensive', 'Counter-Strike: Global Offensive')], max_length=100),
        ),
    ]
