# Generated by Django 3.2.11 on 2023-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20230312_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
