# Generated by Django 3.2.11 on 2023-03-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230330_1115'),
        ('backend', '0007_tournament_finished'),
    ]

    operations = [
    ]
