# Generated by Django 3.2.11 on 2023-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_tournament_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='zdjecie',
            field=models.ImageField(blank=True, default='images/1.png', upload_to='images/'),
        ),
    ]
