# Generated by Django 3.2.14 on 2023-03-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20230312_1549'),
        ('backend', '0009_alter_tournament_zdjecie'),
    ]

    operations = [
    ]
