# Generated by Django 3.2.11 on 2023-03-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20230312_1549'),
        ('backend', '0009_alter_tournament_zdjecie'),
    ]

    operations = [
    ]
