# Generated by Django 3.2.14 on 2023-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge_20230312_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='zdjecie',
            field=models.ImageField(blank=True, default='images/1.png', upload_to='images/'),
        ),
    ]
