# Generated by Django 3.2.11 on 2023-03-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_tournament_zdjecie'),
        ('backend', '0011_auto_20230312_1707'),
    ]

    operations = [
    ]
