# Generated by Django 3.2.11 on 2023-03-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_merge_20230313_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rozgrywki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_turnieju', models.CharField(max_length=100)),
                ('mecz', models.IntegerField(blank=True, null=True)),
                ('faza', models.IntegerField(blank=True, null=True)),
                ('druzyna1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='druzyna1', to='backend.team')),
                ('druzyna2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='druzyna2', to='backend.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='backend.team')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='rozgrywki',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Rozgrywki'),
        ),
    ]
