# Generated by Django 3.2.11 on 2023-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20230313_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozgrywki',
            name='nazwa_rozgrywki',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
