# Generated by Django 3.2.11 on 2023-03-31 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_merge_20230331_0942'),
        ('backend', '0013_auto_20230401_0029'),
    ]

    operations = [
    ]
