# Generated by Django 3.2.11 on 2023-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rozgrywki_nazwa_rozgrywki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozgrywki',
            name='nazwa_rozgrywki',
            field=models.CharField(max_length=100),
        ),
    ]
