# Generated by Django 3.2.11 on 2023-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_rozgrywki_nazwa_rozgrywki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozgrywki',
            name='druzyna1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rozgrywki',
            name='druzyna2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rozgrywki',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
