# Generated by Django 3.2.11 on 2023-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_rozgrywki', models.CharField(max_length=100)),
                ('nazwa_turnieju', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['finished', 'started']},
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/1.png', upload_to=''),
        ),
    ]
