# Generated by Django 3.2.11 on 2023-04-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20230401_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['finished', 'started', 'nazwa']},
        ),
        migrations.AddField(
            model_name='rozgrywki',
            name='zakonczono',
            field=models.BooleanField(default=False),
        ),
    ]
