# Generated by Django 3.2.11 on 2023-03-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20230314_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_team1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_rozgrywki', models.CharField(blank=True, max_length=100, null=True)),
                ('kapitan1', models.CharField(blank=True, max_length=100, null=True)),
                ('wiadomosci_kapitan1', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='Message_team2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_rozgrywki', models.CharField(blank=True, max_length=100, null=True)),
                ('kapitan2', models.CharField(blank=True, max_length=100, null=True)),
                ('wiadomosci_kapitan2', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='message',
            name='kapitan1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='kapitan2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='wiadomosci_kapitan1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='wiadomosci_kapitan2',
        ),
        migrations.AddField(
            model_name='message',
            name='message_team1',
            field=models.ManyToManyField(to='backend.Message_team1'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_team2',
            field=models.ManyToManyField(to='backend.Message_team2'),
        ),
    ]
