# Generated by Django 3.2.11 on 2023-03-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20230314_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozgrywki',
            name='wiadomosci',
        ),
        migrations.AddField(
            model_name='rozgrywki',
            name='message_team1',
            field=models.ManyToManyField(to='backend.Message_team1'),
        ),
        migrations.AddField(
            model_name='rozgrywki',
            name='message_team2',
            field=models.ManyToManyField(to='backend.Message_team2'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
