# Generated by Django 3.2.11 on 2023-04-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_tournament_options'),
        ('backend', '0019_auto_20230402_1913'),
    ]

    operations = [
    ]
