# Generated by Django 3.2.11 on 2023-04-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_merge_20230402_2051'),
        ('backend', '0020_merge_20230402_2114'),
    ]

    operations = [
    ]
