# Generated by Django 3.2.11 on 2023-03-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20230315_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_team1',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='kapitan1',
            new_name='kapitan',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='wiadomosci_kapitan1',
            new_name='wiadomosci',
        ),
        migrations.RemoveField(
            model_name='rozgrywki',
            name='message_team1',
        ),
        migrations.RemoveField(
            model_name='rozgrywki',
            name='message_team2',
        ),
        migrations.AddField(
            model_name='rozgrywki',
            name='message',
            field=models.ManyToManyField(to='backend.Message'),
        ),
        migrations.DeleteModel(
            name='Message_team2',
        ),
    ]
