# Generated by Django 3.2.11 on 2023-03-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20230315_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
